---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: pupzite
# description will be included in the image's metadata
description: Like Bazzite, but with floppy ears 🐶

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: dnf.yml
  - from-file: flatpak.yml
  - from-file: fonts.yml

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - remove-some-bazzite-stuff.sh

  - type: script
    snippets:
      # Make zsh the default shell
      - "useradd -D --shell /usr/bin/zsh"

  - type: os-release
    properties:
      ID: pupzite
      NAME: Pupzite
      PRETTY_NAME: Pupzite
      LOGO: pupzite

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
